services:
  app:
    #    build:
    #      context: . # 指定 Dockerfile 所在的目录为当前目录
    #      dockerfile: Dockerfile # 指定 Dockerfile 的名称
    #      args:
    #        DATABASE_URL_BUILD: "file:./shop.db" # 将你的数据库路径作为构建参数传递

    image: linstar666/fresh-shop:latest
    ports:
      - "3000:3000" # 将容器的 3000 端口映射到主机的 3000 端口
    volumes:
      # 持久化数据库和图片文件
      - db:/app/db
    restart: unless-stopped # 保持 Docker 容器的运维状态，除非手动停止
    environment:
      DATABASE_URL: "file:../../db/shop.db" # 这确保了运行时容器内的 DATABASE_URL 环境变量被设置

volumes:
  db: # 定义一个命名卷用于数据库持久化