export const supplierCreateApi = '/supplier/create'
export const supplierUpdateApi = '/supplier/update'
export const supplierDeleteApi = '/supplier/delete'
export const supplierDetailApi = '/supplier/detail'
export const supplierListApi = '/supplier/list'
export const supplierListAllApi = '/supplier/listAll'

export const productTypeCreateApi = '/productType/create'
export const productTypeUpdateApi = '/productType/update'
export const productTypeDeleteApi = '/productType/delete'
export const productTypeDetailApi = '/productType/detail'
export const productTypeListApi = '/productType/list'
export const productTypeListAllApi = '/productType/listAll'

export const productCreateApi = '/product/create'
export const productUpdateApi = '/product/update'
export const productDeleteApi = '/product/delete'
export const productDetailApi = '/product/detail'
export const productListApi = '/product/list'
export const productListAllApi = '/product/listAll'

export const customerAddressCreateApi = '/customerAddress/create'
export const customerAddressUpdateApi = '/customerAddress/update'
export const customerAddressDeleteApi = '/customerAddress/delete'
export const customerAddressDetailApi = '/customerAddress/detail'
export const customerAddressListApi = '/customerAddress/list'
export const customerAddressListAllApi = '/customerAddress/listAll'

export const customerCreateApi = '/customer/create'
export const customerUpdateApi = '/customer/update'
export const customerDeleteApi = '/customer/delete'
export const customerDetailApi = '/customer/detail'
export const customerListApi = '/customer/list'
export const customerListAllApi = '/customer/listAll'

export const groupBuyCreateApi = '/groupBuy/create'
export const groupBuyUpdateApi = '/groupBuy/update'
export const groupBuyDeleteApi = '/groupBuy/delete'
export const groupBuyDetailApi = '/groupBuy/detail'
export const groupBuyListApi = '/groupBuy/list'
export const groupBuyListAllApi = '/groupBuy/listAll'

export const orderCreateApi = '/order/create'
export const orderUpdateApi = '/order/update'
export const orderDeleteApi = '/order/delete'
export const orderDetailApi = '/order/detail'
export const orderListApi = '/order/list'
export const orderListAllApi = '/order/listAll'
export const orderRefundApi = '/order/refund'

export const globalSettingUpsertApi = '/globalSetting/upsert'
export const globalSettingDetailApi = '/globalSetting/detail'

export const analysisCountApi = '/analysis/count'
export const analysisRankApi = '/analysis/rank'
