export const supplierCreateApi = '/supplier/create'
export const supplierUpdateApi = '/supplier/update'
export const supplierDeleteApi = '/supplier/delete'
export const supplierDetailApi = '/supplier/detail'
export const supplierListApi = '/supplier/list'

export const productTypeCreateApi = '/productType/create'
export const productTypeUpdateApi = '/productType/update'
export const productTypeDeleteApi = '/productType/delete'
export const productTypeDetailApi = '/productType/detail'
export const productTypeListApi = '/productType/list'
export const productTypeListAllApi = '/productType/listAll'

export const productCreateApi = '/product/create'
export const productUpdateApi = '/product/update'
export const productDeleteApi = '/product/delete'
export const productDetailApi = '/product/detail'
export const productListApi = '/product/list'

export const customerAddressCreateApi = '/customerAddress/create'
export const customerAddressUpdateApi = '/customerAddress/update'
export const customerAddressDeleteApi = '/customerAddress/delete'
export const customerAddressDetailApi = '/customerAddress/detail'
export const customerAddressListApi = '/customerAddress/list'
export const customerAddressListAllApi = '/customerAddress/listAll'

export const customerCreateApi = '/customer/create'
export const customerUpdateApi = '/customer/update'
export const customerDeleteApi = '/customer/delete'
export const customerDetailApi = '/customer/detail'
export const customerListApi = '/customer/list'
